services:
  - type: web
    name: bingo-embedded-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MAX_PLAYERS
        value: 1
