const express = require('express');
const http = require('http');
const { Server } = require('socket.io');

const app = express();
const server = http.createServer(app);
const io = new Server(server);

const PORT = process.env.PORT || 3000;

// Serve static files from the "public" directory
app.use(express.static('public'));

let webPlayers = [];
const MAX_PLAYERS = 3;

io.on('connection', (socket) => {
    console.log('A client connected:', socket.id);

    // Register a WebPlayer
    socket.on('register_player', () => {
        if (webPlayers.length < MAX_PLAYERS) {
            webPlayers.push(socket.id);
            console.log(`Player registered: ${socket.id}. Total players: ${webPlayers.length}`);
            socket.emit('player_registered', { success: true, playerId: socket.id });
        } else {
            console.log(`Registration failed: ${socket.id}. Max players reached.`);
            socket.emit('player_registered', { success: false, message: 'Max players reached' });
        }
    });

    // Handle number generated from Arduino
    socket.on('number_generated', (data) => {
        console.log('Number generated by Arduino:', data);
        // Broadcast the generated number to all connected clients (players)
        io.emit('new_number', data);
    });

    // Handle bingo claimed by a player
    socket.on('bingo_claimed', (data) => {
        console.log(`Bingo claimed by player ${socket.id}`, data);
        // Broadcast to all clients that someone has won
        io.emit('game_over', { winner: socket.id, name: data.name, time: data.time });
    });

    // Handle disconnect
    socket.on('disconnect', () => {
        console.log('A client disconnected:', socket.id);
        const index = webPlayers.indexOf(socket.id);
        if (index !== -1) {
            webPlayers.splice(index, 1);
            console.log(`Player removed. Total players: ${webPlayers.length}`);
        }
    });
});

server.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`);
});
