const express = require('express');
const http = require('http');
const { Server } = require('socket.io');

const app = express();
const server = http.createServer(app);
const io = new Server(server);

const PORT = process.env.PORT || 3000;

app.use(express.static('public'));

let activeLobbies = {};
const MAX_PLAYERS_PER_LOBBY = 5;

io.on('connection', (socket) => {
    console.log('A client connected:', socket.id);

    socket.emit('lobbies_update', Object.values(activeLobbies));

    socket.on('create_lobby', (data) => {
        const lobbyId = 'lobby_' + socket.id;
        activeLobbies[lobbyId] = {
            id: lobbyId,
            name: ${data.playerName}''s Lobby,
            leader: socket.id,
            players: [{ id: socket.id, name: data.playerName }],
            maxPlayers: MAX_PLAYERS_PER_LOBBY,
            gameActive: false
        };
        socket.join(lobbyId);
        socket.currentLobby = lobbyId;
        console.log(Lobby created:  by );
        
        io.emit('lobbies_update', Object.values(activeLobbies));
        socket.emit('lobby_joined', activeLobbies[lobbyId]);
    });

    socket.on('join_lobby', (data) => {
        const lobby = activeLobbies[data.lobbyId];
        if (lobby && lobby.players.length < lobby.maxPlayers && !lobby.gameActive) {
            lobby.players.push({ id: socket.id, name: data.playerName });
            socket.join(data.lobbyId);
            socket.currentLobby = data.lobbyId;
            console.log(Player  joined lobby: );
            
            io.emit('lobbies_update', Object.values(activeLobbies));
            socket.emit('lobby_joined', lobby);
            io.to(data.lobbyId).emit('lobby_updated', lobby);
        } else {
            socket.emit('lobby_error', { message: 'Cannot join lobby' });
        }
    });

    socket.on('start_game', () => {
        const lobbyId = socket.currentLobby;
        if (lobbyId && activeLobbies[lobbyId] && activeLobbies[lobbyId].leader === socket.id) {
            activeLobbies[lobbyId].gameActive = true;
            io.emit('lobbies_update', Object.values(activeLobbies));
            io.to(lobbyId).emit('game_started');
        }
    });

    socket.on('number_generated', (data) => {
        console.log('Number generated by Arduino:', data);
        io.emit('new_number', data);
    });

    socket.on('bingo_claimed', (data) => {
        const lobbyId = socket.currentLobby;
        console.log(Bingo claimed by player , data);
        if (lobbyId && activeLobbies[lobbyId]) {
            activeLobbies[lobbyId].gameActive = false;
            io.to(lobbyId).emit('game_over', { winner: data.name, time: data.time });
            io.emit('lobbies_update', Object.values(activeLobbies));
        } else {
            io.emit('game_over', { winner: data.name, time: data.time });
        }
    });

    socket.on('disconnect', () => {
        console.log('A client disconnected:', socket.id);
        const lobbyId = socket.currentLobby;
        if (lobbyId && activeLobbies[lobbyId]) {
            const lobby = activeLobbies[lobbyId];
            const playerIndex = lobby.players.findIndex(p => p.id === socket.id);
            if (playerIndex !== -1) {
                lobby.players.splice(playerIndex, 1);
                if (lobby.players.length === 0) {
                    delete activeLobbies[lobbyId];
                } else if (lobby.leader === socket.id) {
                    lobby.leader = lobby.players[0].id;
                }
                io.to(lobbyId).emit('lobby_updated', activeLobbies[lobbyId] || null);
                io.emit('lobbies_update', Object.values(activeLobbies));
            }
        }
    });
});

server.listen(PORT, () => {
    console.log(Server is running on port );
});
